export const defaultImage = '/customers/customer-icon.png';

export const links = [
  {
    id: 1,
    name: 'home',
    href: '/',
  },
  {
    id: 2,
    name: 'sources',
    href: '/sources',
  },
  {
    id: 3,
    name: 'top stories',
    href: '/top-stories',
  },
  {
    id: 4,
    name: 'all news',
    href: '/all-news',
  },
  {
    id: 5,
    name: 'contact',
    href: '/contact',
  },
];

export const locales = {
  ar: 'Argentina',
  am: 'Armenia',
  au: 'Australia',
  at: 'Austria',
  by: 'Belarus',
  be: 'Belgium',
  bo: 'Bolivia',
  br: 'Brazil',
  bg: 'Bulgaria',
  ca: 'Canada',
  cl: 'Chile',
  cn: 'China',
  co: 'Colombia',
  hr: 'Croatia',
  cz: 'Czechia',
  ec: 'Ecuador',
  eg: 'Egypt',
  fr: 'France',
  de: 'Germany',
  gr: 'Greece',
  hn: 'Honduras',
  hk: 'Hong Kong',
  in: 'India',
  id: 'Indonesia',
  ir: 'Iran',
  ie: 'Ireland',
  il: 'Israel',
  it: 'Italy',
  jp: 'Japan',
  kr: 'Korea',
  mx: 'Mexico',
  nl: 'Netherlands',
  nz: 'New Zealand',
  ni: 'Nicaragua',
  pk: 'Pakistan',
  pa: 'Panama',
  pe: 'Peru',
  pl: 'Poland',
  pt: 'Portugal',
  qa: 'Qatar',
  ro: 'Romania',
  ru: 'Russia',
  sa: 'Saudi Arabia',
  za: 'South Africa',
  es: 'Spain',
  ch: 'Switzerland',
  sy: 'Syria',
  tw: 'Taiwan',
  th: 'Thailand',
  tr: 'Turkey',
  ua: 'Ukraine',
  gb: 'United Kingdom',
  us: 'United States Of America',
  uy: 'Uruguay',
  ve: 'Venezuela',
};

export const languages = {
  ar: 'Arabic',
  bg: 'Bulgarian',
  bn: 'Bengali',
  cs: 'Czech',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  en: 'English',
  es: 'Spanish',
  et: 'Estonian',
  fa: 'Persian',
  fi: 'Finnish',
  fr: 'French',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hu: 'Hungarian',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  ko: 'Korean',
  lt: 'Lithuanian',
  multi: 'Multi',
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  pt: 'Portuguese',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  sv: 'Swedish',
  ta: 'Tamil',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  vi: 'Vietnamese',
  zh: 'Chinese',
};

export const categories = {
  general: 'general',
  science: 'science',
  sports: 'sports',
  business: 'business',
  health: 'health',
  entertainment: 'entertainment',
  tech: 'tech',
  politics: 'politics',
  food: 'food',
  travel: 'travel',
};
